[package]
name = "flow-settings"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
flow-config = { path = "../flow-config" }
flow-secrets = { path = "../flow-secrets" }
tracing = "0.1"
